# Generated by Django 5.2.14 on 2026-06-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
