# Generated by Django 6.0.3 on 2026-03-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
