# Generated by Django 6.0.3 on 2026-05-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_stripe_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Thanh toán khi nhận hàng (COD)'), ('Stripe', 'Thanh toán qua Stripe (Thẻ Quốc tế)'), ('VNPay', 'Thanh toán qua VNPay (Ngân hàng Nội địa)')], default='COD', max_length=20),
        ),
    ]
