# Generated by Django 5.2.14 on 2026-06-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Thanh toán khi nhận hàng (COD)'), ('Stripe', 'Thanh toán qua Stripe (Thẻ Quốc tế)'), ('VNPay', 'Thanh toán qua VNPay (Ngân hàng Nội địa)'), ('MoMo', 'Thanh toán qua Ví MoMo')], default='COD', max_length=20),
        ),
    ]
